# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=50)),
                ('is_completed', models.BooleanField()),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('brigade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brigade')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Task')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WorkerType'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='app.Worker'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='member2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member2', to='app.Worker'),
        ),
        migrations.AddField(
            model_name='brigade',
            name='member3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member3', to='app.Worker'),
        ),
    ]
